// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwhW_cfZyVKsGlkeMizmb8wyftDpaLyyo',
    appId: '1:845572128747:ios:eec6298bcbe8ef65ffe3ae',
    messagingSenderId: '845572128747',
    projectId: 'mediassist-ae070',
    storageBucket: 'mediassist-ae070.firebasestorage.app',
    iosBundleId: 'com.example.mediassist',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwhW_cfZyVKsGlkeMizmb8wyftDpaLyyo',
    appId: '1:845572128747:ios:eec6298bcbe8ef65ffe3ae',
    messagingSenderId: '845572128747',
    projectId: 'mediassist-ae070',
    storageBucket: 'mediassist-ae070.firebasestorage.app',
    iosBundleId: 'com.example.mediassist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIcNrRWIVOMff3EtnyvdtEcF-gluPOJdE',
    appId: '1:845572128747:web:306d8a3bbf490758ffe3ae',
    messagingSenderId: '845572128747',
    projectId: 'mediassist-ae070',
    authDomain: 'mediassist-ae070.firebaseapp.com',
    storageBucket: 'mediassist-ae070.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIcNrRWIVOMff3EtnyvdtEcF-gluPOJdE',
    appId: '1:845572128747:web:306d8a3bbf490758ffe3ae',
    messagingSenderId: '845572128747',
    projectId: 'mediassist-ae070',
    authDomain: 'mediassist-ae070.firebaseapp.com',
    storageBucket: 'mediassist-ae070.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVhKKFAf9EGjEVxlv85CWKaY3qypWLRWU',
    appId: '1:845572128747:android:47cc444576b9ea67ffe3ae',
    messagingSenderId: '845572128747',
    projectId: 'mediassist-ae070',
    storageBucket: 'mediassist-ae070.firebasestorage.app',
  );
}
